# Generated by Django 3.2.6 on 2021-08-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210814_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='interestingUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='nonInterestingUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.TextField()),
            ],
        ),
    ]
