# Generated by Django 3.2.6 on 2021-08-14 12:32

from django.db import migrations
from ..import scrapping

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210814_1758'),
    ]
    def getJobDetails(apps,schema_editor):
        Job=apps.get_model('api','nonInterestingUrls')
        all_jobs=[]
        internshala_job=scrapping.get_internshala_details()
        talentrack_job=scrapping.get_talentrack_details()
        iim_job=scrapping.get_iimjobs_details()
        all_jobs=talentrack_job+internshala_job+iim_job
        for job in all_jobs:
            job=Job(urls=job)
            job.save()
    operations = [
        migrations.RunPython(getJobDetails),
    ]
